packages:
  - apps/*
  - packages/*

allowBuilds:
  better-sqlite3: true
  esbuild: true
  tree-sitter-go: false
  tree-sitter-javascript: false
  tree-sitter-python: false
  tree-sitter-rust: false
  tree-sitter-typescript: false

enableGlobalVirtualStore: true
