import { FullPageErrorAlert } from '@base/components/common/FullPageErrorAlert'
import { sansFont, serifFont } from '@base/lib/fonts'
import { apiClient } from '@base/services'
import type { Metadata } from 'next'
import { redirect } from 'next/navigation'
import { PublicEnvScript } from 'next-runtime-env'

import { SiteLayout } from '~/layout/container/SiteLayout'
import Footer from '~/layout/footer/Footer'
import Header from '~/layout/header/Header'
import { Content } from '~/layout/main/Content'
import { WebAppProviders } from '~/providers/Providers'
import { AggregationDataProvider } from '~/providers/root/AggregationDataProvider'

export const metadata: Metadata = {
  title: 'Marchen',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const aggregateData = await apiClient.aggregate.get().catch((error) => {
    if (error.response?.status === 404) {
      return redirect('/setup')
    }
  })

  if (!aggregateData) {
    return (
      <html lang="zh-CN" data-theme="light" suppressHydrationWarning>
        <head>
          <PublicEnvScript />
        </head>
        <body
          className={`${sansFont.variable} ${serifFont.variable} m-0 h-full p-0 font-sans`}
        >
          <div className="flex h-full items-center justify-center">
            <FullPageErrorAlert message="无数据" />
          </div>
        </body>
      </html>
    )
  }
  return (
    <html lang="zh-CN" data-theme="light" suppressHydrationWarning>
      <head>
        <PublicEnvScript />
      </head>
      <body
        className={`${sansFont.variable} ${serifFont.variable} font-sans antialiased`}
      >
        <WebAppProviders>
          <AggregationDataProvider value={aggregateData}>
            <SiteLayout>
              <Header />
              <Content>{children}</Content>
              <Footer />
            </SiteLayout>
          </AggregationDataProvider>
        </WebAppProviders>
      </body>
    </html>
  )
}
