import { sansFont, serifFont } from '@base/lib/fonts'
import type { Metadata } from 'next'

import { SiteLayout } from '~/layout/container/SiteLayout'
import Footer from '~/layout/footer/Footer'
import Header from '~/layout/header/Header'
import { Content } from '~/layout/main/Content'
import { MarchenProviders } from '~/providers'

export const metadata: Metadata = {
  title: 'Marchen',
  description: 'Generated by create next app',
}

export default function MarchenLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="zh-CN" data-theme="light" suppressHydrationWarning>
      <body
        className={`${sansFont.variable} ${serifFont.variable} font-sans antialiased`}
      >
        <MarchenProviders>
          <SiteLayout>
            <Header />
            <Content>{children}</Content>
            <Footer />
          </SiteLayout>
        </MarchenProviders>
      </body>
    </html>
  )
}
